### ISSUE TITLE
Inline script fails as stdin not in gzip format

### ISSUE THREAD

**Issue by murdoaird** [johnmccabe/vagrant-brooklyn-getting-started#1]
When running the **vagrant up brooklyn** command a inline script fails as it appears that an input is not in the expected gzip format...

**Error returned:**
==> brooklyn: gzip: stdin: not in gzip format
==> brooklyn: tar: Child returned status 1
==> brooklyn: tar: Error is not recoverable: exiting now
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

Versions:
- VirtualBox 5.0.10
- Vagrant 1.7.4
- OS X El Cap (10.11.1)

Any guidance appreciated. Thanks. 

**Full log returned:**
MacBook-Pro:vagrant-brooklyn-getting-started murdoaird$ vagrant up brooklyn
Bringing machine 'brooklyn' up with 'virtualbox' provider...
==> brooklyn: Box 'ubuntu/vivid64' could not be found. Attempting to find and install...
    brooklyn: Box Provider: virtualbox
    brooklyn: Box Version: >= 0
==> brooklyn: Loading metadata for box 'ubuntu/vivid64'
    brooklyn: URL: https://atlas.hashicorp.com/ubuntu/vivid64
==> brooklyn: Adding box 'ubuntu/vivid64' (v20151201.0.0) for provider: virtualbox
    brooklyn: Downloading: https://atlas.hashicorp.com/ubuntu/boxes/vivid64/versions/20151201.0.0/providers/virtualbox.box
==> brooklyn: Successfully added box 'ubuntu/vivid64' (v20151201.0.0) for 'virtualbox'!
==> brooklyn: Importing base box 'ubuntu/vivid64'...
==> brooklyn: Matching MAC address for NAT networking...
==> brooklyn: Checking if box 'ubuntu/vivid64' is up to date...
==> brooklyn: Setting the name of the VM: brooklyn
==> brooklyn: Clearing any previously set forwarded ports...
==> brooklyn: Clearing any previously set network interfaces...
==> brooklyn: Preparing network interfaces based on configuration...
    brooklyn: Adapter 1: nat
    brooklyn: Adapter 2: hostonly
==> brooklyn: Forwarding ports...
    brooklyn: 8081 => 8081 (adapter 1)
    brooklyn: 22 => 2222 (adapter 1)
==> brooklyn: Running 'pre-boot' VM customizations...
==> brooklyn: Booting VM...
==> brooklyn: Waiting for machine to boot. This may take a few minutes...
    brooklyn: SSH address: 127.0.0.1:2222
    brooklyn: SSH username: vagrant
    brooklyn: SSH auth method: private key
    brooklyn: Warning: Connection timeout. Retrying...
    brooklyn: 
    brooklyn: Vagrant insecure key detected. Vagrant will automatically replace
    brooklyn: this with a newly generated keypair for better security.
    brooklyn: 
    brooklyn: Inserting generated public key within guest...
    brooklyn: Removing insecure key from the guest if it's present...
    brooklyn: Key inserted! Disconnecting and reconnecting using new SSH key...
==> brooklyn: Machine booted and ready!
==> brooklyn: Checking for guest additions in VM...
    brooklyn: The guest additions on this VM do not match the installed version of
    brooklyn: VirtualBox! In most cases this is fine, but in rare cases it can
    brooklyn: prevent things such as shared folders from working properly. If you see
    brooklyn: shared folder errors, please make sure the guest additions within the
    brooklyn: virtual machine match the version of VirtualBox you have installed on
    brooklyn: your host and reload your VM.
    brooklyn: 
    brooklyn: Guest Additions Version: 4.3.34
    brooklyn: VirtualBox Version: 5.0
==> brooklyn: Setting hostname...
==> brooklyn: Configuring and enabling network interfaces...
==> brooklyn: Mounting shared folders...
    brooklyn: /vagrant => /Users/murdoaird/Documents/workspace/vagrant-brooklyn-getting-started
==> brooklyn: Running provisioner: shell...
    brooklyn: Running: inline script
==> brooklyn: Running provisioner: shell...
    brooklyn: Running: inline script
==> brooklyn: 
==> brooklyn: gzip: stdin: not in gzip format
==> brooklyn: tar: Child returned status 1
==> brooklyn: tar: Error is not recoverable: exiting now
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by johnmccabe** [comment]
That should work for you now @murdoaird it was due to the urls changing on the ASF mirrors after the project graduated, fixed the brooklyn 0.8.0 download url in the `servers.yaml` and its working again.

**Comment by johnmccabe** [comment]
let me know if it works for you and we can close this

**Comment by murdoaird** [comment]
Works perfectly. Thanks.
